[project]
name = "ccnlthd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.0.1",
    "djangorestframework>=3.14",
    "psycopg[binary]>=3.3.2",
    "python-dotenv>=1.2.1",
]
